---
name: Build bats container image

on:
  push:
    branches: ["main"]
    paths:
      - "bats/**"
  pull_request:
    branches: ["main"]
    paths:
      - "bats/**"

jobs:
  build-bats:
    uses: ./.github/workflows/generic-docker-build.yml
    with:
      image-folder: bats
      image-tag: v1.10.0-curl
