name: Reusable Docker Build and Scan

on:
  workflow_call:
    inputs:
      image-folder:
        required: true
        type: string
      image-name:
        required: false
        type: string
      image-tag:
        required: true
        type: string
      skip-dirs:
        required: false
        type: string
        default: /usr/local/bin
      ignored-dockerfile-lint-rules:
        required: false
        type: string
        default: "DL3008,DL3015,DL3018"

env:
  REGISTRY: ghcr.io

jobs:
  build-scan-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Build informations
        id: build-info
        run: |
          echo "Building ${{ inputs.image-name || inputs.image-folder }} (tag ${{ inputs.image-tag }})"
          echo "ci-image-name=${{ env.REGISTRY }}/${{ github.repository }}/${{ inputs.image-name || inputs.image-folder }}:ci-${{ github.sha }}" >> $GITHUB_OUTPUT
          echo "image-name=${{ env.REGISTRY }}/${{ github.repository }}/${{ inputs.image-name || inputs.image-folder }}:${{ inputs.image-tag }}" >> $GITHUB_OUTPUT

      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3.5.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push temporary ci Docker image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: ${{ inputs.image-folder }}
          push: true
          tags: ${{ steps.build-info.outputs.ci-image-name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ steps.build-info.outputs.ci-image-name }}
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          skip-dirs: ${{ inputs.skip-dirs }}
          trivyignores: "${{ inputs.image-folder }}/.trivyignore"
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"
        env:
          TRIVY_USERNAME: ${{ github.actor }}
          TRIVY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image after trivy scan
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: ${{ inputs.image-folder }}
          tags: ${{ steps.build-info.outputs.image-name }}
          push: ${{ github.ref == 'refs/heads/main' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: docker/login-action@v3.5.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Dockerfile linting
        uses: hadolint/hadolint-action@v3.2.0
        with:
          dockerfile: ${{ inputs.image-folder }}/Dockerfile
          ignore: ${{ inputs.ignored-dockerfile-lint-rules }}
